# docker-compose.yml
version: '3.9'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: jenkins
    ports:
      - 8083:8080
      # - 50003:50000
    container_name: bpor-jenkins
    volumes:
      - ./jenkins:/var/jenkins_home:rw